feat: update drug datasets + sync db + cron (#16)
* refactor: code

* feat: update datasets script

* feat: update drug datasets command

* chore: unable changes on distant old datasets

* feat: update datasets cron

* refactor: env var

* fix: code

* fix: last fix

---------

Co-authored-by: Sophie <sophie@nalyze.team>

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -2,3 +2,10 @@
 . "$(dirname -- "$0")/_/husky.sh"
 
 npx lint-staged
+
+if git diff --cached --name-only | grep -q "src/datasets/old"; then
+  echo "Error: Changes to src/datasets/old are not allowed."
+  git restore --staged src/datasets/old
+  git update-index --skip-worktree src/datasets/old/*
+  exit 1
+fi
